


<HTML>
<html lang="en-US" xml:lang="en-US" xmlns=""/>
<head>
<title> Entoto Technical & Vocational Training college Online Inventory Management Systems </title>
<link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
<link rel="stylesheet" href="css/style.css">
<link rel="stylesheet" media="screen and (max-width: 768px)" href="css/mobile.css">
<link rel="stylesheet" media="screen and (min-width: 1100px)" href="css/widescreen.css">
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
<meta name="Keywords" content="XML,tutorial,HTML,DHTML,CSS,XSL,XHTML,JavaScript,ASP,ADO,VBScript,DOM,W3C,authoring,programming,learning,beginner's guide,primer,lessons,school,howto,reference,free,examples,samples,source code,demos,tips,links,FAQ,tag list,forms,frames,color tables,Cascading Style Sheets,Active Server Pages,Dynamic HTML,Internet database development,Webbuilder,Sitebuilder,Webmaster,HTMLGuide,SiteExpert" />
<meta name="Description" content="HTML XHTML CSS JavaScript XML XSL ASP SQL ADO VBScript Tutorials References Examples" />
<link rel="stylesheet" type="text/css" href="index's_file/globalcss.css" />
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "../https@ssl.\default.htm" : "../www./default.htm");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
var pageTracker = _gat._getTracker("UA-3855518-1");
pageTracker._initData();
pageTracker._trackPageview();
</script>





</head>
<body onLoad="timeimgs('1');">
  <nav id="navbar">
    <h1 class="logo">
      <span class="text-primary">
        <img align="left" border="0" src="imag/logo1.jpg"/> 
		 <h1><center> እንጦጦ ፖሊ ቴክኒክ ኮሌጅ</br> ENTOTO TECHNICAL AND VOCATIONAL TRAINNG COLLEGE</center></h1></span>
    </h1>

    <ul>
      <li><a href="home.php">Home</a></li>
      <li><a href="aboutus.php">About</a></li>
      <li><a href="services.php">Services</a></li>
      <li><a href="login.php">Login</a></li>
    </ul>
  </nav>

<section id="who">
    <div class="who-img"></div>
    <div class="who-text bg-dark p-2">
	<h2 class="m-heading"><span class="text-primary">Who</span> We Are</h2>
    <p>Entoto Technical & Vocational Training college store office was established during the time of 
	 the college establishment and It is developed from time to time with the development of the College. 
	 As it is developed from time to time it increases its capacity by increasing 
	 the number of workers in the office.</p>
	 <p>We are proud to offer exceptional education at an affordable cost.
	 With low tuition rates and financial assistance given to most of our students each year, 
	 our college is the most affordable and best quality four-year college in the region. 
	 Our value, combined with personalized attention from caring professors and staff, 
	 a friendly campus community, and opportunities to learn in and outside the classroom, 
	 makes our college a great place for students to thrive and advance their futures.</p>
	 <h1>Contact address</h1>
	 <p>Tel No:-<br>
	 0581110051</br>
	 0581117019</br>
	 0581117000</p>
    </div>
	<div class="who-img"></div>
  </section>

<table width="953px" height="42px" border="1" background-color="#282828">
<tr width="953"style="margin-bottom:1px;margin-top:1px;background-color:#606060  ;border:0px solid #ffffff" border="0px" cellpadding="10" cellspacing="0">
<td valign="top" align="center">

<font color="#fef943" face="arial">&copy;2022 @ Entoto Technical & Vocational Training college Online Inventory Management System.</font>
</td></tr></table>






</td></tr></table>
</center>
</body>
</html>
