<HTML>
<html lang="en-US" xml:lang="en-US" xmlns=""/>
<head>
<title> ENTOTO TECHNICAL AND VOCATIONAL TRAINNG COLLEGE </title>
<link rel="shortcut icon" href="favicon.ico" type="imagese/x-icon" />
<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" />
<link rel="stylesheet" href="css/style.css">
<link rel="stylesheet" href="css/slide.css" >
<link rel="stylesheet" media="screen and (max-width: 768px)" href="css/mobile.css" />
<link rel="stylesheet" media="screen and (min-width: 1100px)" href="css/widescreen.css" />
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
<meta name="Keywords" content="XML,tutorial,HTML,DHTML,CSS,XSL,XHTML,JavaScript,ASP,ADO,VBScript,DOM,W3C,authoring,programming,learning,beginner's guide,primer,lessons,school,howto,reference,free,examples,samples,source code,demos,tips,links,FAQ,tag list,forms,frames,color tables,Cascading Style Sheets,Active Server Pages,Dynamic HTML,Internet database development,Webbuilder,Sitebuilder,Webmaster,HTMLGuide,SiteExpert" />
<meta name="Description" content="HTML XHTML CSS JavaScript XML XSL ASP SQL ADO VBScript Tutorials References Examples" />
<meta http-equiv="refresh" content="">
<link rel="stylesheet" type="text/css" href="index's_file/globalcss.css" />
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "../https@ssl.\default.htm" : "../www./default.htm");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
var pageTracker = _gat._getTracker("UA-3855518-1");
pageTracker._initData();
pageTracker._trackPageview();
</script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
</head>
<body onLoad="timeimgs('1');">
  <nav id="navbar">
    <h1 class="logo">
      <span class="text-primary">
        <img align="left" border="0" src="imag/logo1.jpg"/> 
		 <h3><center> እንጦጦ ፖሊ ቴክኒክ ኮሌጅ</br> ENTOTO TECHNICAL AND VOCATIONAL TRAINNG COLLEGE</center></h3></span>
    </h1>

    <ul>
      <li><a href="home.php">Home</a></li>
      <li><a href="aboutus.php">About</a></li>
      <li><a href="services.php">Services</a></li>
      <li><a href="login.php">Login</a></li>
    </ul>
  </nav>

  <section id="who">
<div class="who-text bg-dark p-2">
<div id="carouselFade" class="carousel slide carousel-fade" data-ride="carousel">

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
            <div class="item active">  
                <div class="carousel-caption">
              </div>
            </div>
            <div class="item"> 
                <div class="carousel-caption">

                </div>
            </div>
            <div class="item"> 
                <div class="carousel-caption">
                  
                </div>
            </div>
        </div>
    </div>
	 </div>
  </section>
    


<table width="953px" height="42px" border="1" background-color="#282828">
<tr width="953"style="margin-bottom:1px;margin-top:1px;background-color:#606060  ;border:0px solid #ffffff" border="0px" cellpadding="10" cellspacing="0">
<td valign="top" align="center">

<font color="#fef943" face="arial">&copy; 2022 @ ENTOTO TECHNICAL AND VOCATIONAL TRAINNG COLLEGE Online Inventory Management System.</font>
</td></tr></table>






</td></tr></table>

</body>

</html>
